// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1-gHwWLqJQ5ZoL5Q4rY7qJk6UHp2BQY',
    appId: '1:653926047238:web:gv-web-app',
    messagingSenderId: '653926047238',
    projectId: 'grievance-app-11680',
    authDomain: 'grievance-app-11680.firebaseapp.com',
    storageBucket: 'grievance-app-11680.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1-gHwWLqJQ5ZoL5Q4rY7qJk6UHp2BQY',
    appId: '1:653926047238:android:gv-android-app',
    messagingSenderId: '653926047238',
    projectId: 'grievance-app-11680',
    storageBucket: 'grievance-app-11680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1-gHwWLqJQ5ZoL5Q4rY7qJk6UHp2BQY',
    appId: '1:653926047238:ios:gv-ios-app',
    messagingSenderId: '653926047238',
    projectId: 'grievance-app-11680',
    storageBucket: 'grievance-app-11680.appspot.com',
    iosBundleId: 'com.government.grievance.gv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1-gHwWLqJQ5ZoL5Q4rY7qJk6UHp2BQY',
    appId: '1:653926047238:ios:gv-macos-app',
    messagingSenderId: '653926047238',
    projectId: 'grievance-app-11680',
    storageBucket: 'grievance-app-11680.appspot.com',
    iosBundleId: 'com.government.grievance.gv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe1-gHwWLqJQ5ZoL5Q4rY7qJk6UHp2BQY',
    appId: '1:653926047238:web:gv-windows-app',
    messagingSenderId: '653926047238',
    projectId: 'grievance-app-11680',
    authDomain: 'grievance-app-11680.firebaseapp.com',
    storageBucket: 'grievance-app-11680.appspot.com',
  );
}
